config/routes.rb
Board::Application.routes.draw do

  root to: 'dashboards#index'

  resources :metrics do
    collection { post :sort }
    member do
      get 'move_higher'
      get 'move_lower'
      get 'move_to_top'
      get 'move_to_bottom'
    end
  end

  resources :dashboards do
    member do
      get 'board'
    end
  end

  post 'api/stats', to: 'metrics#stats', as: :stats
  get 'help', to: 'welcome#help', as: :help

  get 'login', to: 'admin_sessions#new', as: 'login'
  get 'logout', to: 'admin_sessions#destroy', as: 'logout'
  resources :admin_sessions

end

app/models/metric.rb
class Metric < ActiveRecord::Base
  has_many :values, :dependent => :destroy
  has_many :assignments
  has_many :dashboards, :through => :assignments
  attr_accessible :dashboard_ids, :name, :description, :value_type, :string_value,
    :integer_value, :decimal_value, :position, :color, :width, :font_size, :refresh_every

  acts_as_list :scope => :dashboard

  def color
    return super if super
    '#86CBDD'
  end

  def width
    return super if super
    1
  end

  def font_size
    return super if super
    50
  end

  def refresh_every
    return super if super
    0
  end

end

app/controllers/metrics_controller.rb
class MetricsController < ApplicationController
  before_filter :authorize, except: [:stats]

  # curl -s -d "value=Ola1c&metric_id=3" http://localhost:3000/api/stats
  def stats
    value = params[:value]
    metric = Metric.find(params[:metric_id])

    if metric.value_type == "integer"
      metric.update_attribute(:integer_value, value)
    elsif metric.value_type == "knob"
      metric.update_attribute(:integer_value, value)
    elsif metric.value_type == "line"
      metric.update_attribute(:decimal_value, value)
      value = metric.values.create(decimal_value: value)
    else # string and default
      metric.update_attribute(:string_value, value)
    end

    render xml: value
  end

  # GET /metrics
  # GET /metrics.json
  def index
    @metrics = Metric.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @metrics }
    end
  end

  # GET /metrics/1
  # GET /metrics/1.json
  def show
    @metric = Metric.find(params[:id])

    # respond_to do |format|
    #   format.html # show.html.erb
    #   format.js { render partial: 'widget', locals: { object: @metric }, layout: nil }
    #   format.json { render json: @metric }
    # end
    render partial: 'widget', locals: { metric: @metric }#, layout: nil
  end

  # GET /metrics/new
  # GET /metrics/new.json
  def new
    @metric = Metric.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @metric }
    end
  end

  # GET /metrics/1/edit
  def edit
    @metric = Metric.find(params[:id])
  end

  # POST /metrics
  # POST /metrics.json
  def create
    @metric = Metric.new(params[:metric])

    respond_to do |format|
      if @metric.save
        format.html { redirect_to @metric, notice: 'Metric was successfully created.' }
        format.json { render json: @metric, status: :created, location: @metric }
      else
        format.html { render action: "new" }
        format.json { render json: @metric.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /metrics/1
  # PUT /metrics/1.json
  def update
    @metric = Metric.find(params[:id])

    respond_to do |format|
      if @metric.update_attributes(params[:metric])
        format.html { redirect_to metrics_path, notice: 'Metric was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @metric.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /metrics/1
  # DELETE /metrics/1.json
  def destroy
    @metric = Metric.find(params[:id])
    @metric.destroy

    respond_to do |format|
      format.html { redirect_to metrics_url }
      format.json { head :no_content }
    end
  end

  def sort
    position = params[:position].to_i + 1
    dashboard = Dashboard.find(params[:dashboard_id])
    dashboard.metrics.order(:position).each_with_index { |metric, i| metric.update_attribute(:position, i + 1) }
    dashboard.metrics.find(params[:metric_id]).insert_at(position)
    render nothing: true
  end

  def move_higher
    dashboard = Dashboard.find(params[:dashboard_id])
    dashboard.metrics.order(:position).each_with_index { |metric, i| metric.update_attribute(:position, i + 1) }
    dashboard.metrics.find(params[:id]).move_higher
    redirect_to dashboard_path(params[:dashboard_id])
  end

  def move_lower
    dashboard = Dashboard.find(params[:dashboard_id])
    dashboard.metrics.order(:position).each_with_index { |metric, i| metric.update_attribute(:position, i + 1) }
    dashboard.metrics.find(params[:id]).move_lower
    redirect_to dashboard_path(params[:dashboard_id])
  end

  def move_to_top
    dashboard = Dashboard.find(params[:dashboard_id])
    dashboard.metrics.order(:position).each_with_index { |metric, i| metric.update_attribute(:position, i + 1) }
    dashboard.metrics.find(params[:id]).move_to_top
    redirect_to dashboard_path(params[:dashboard_id])
  end

  def move_to_bottom
    dashboard = Dashboard.find(params[:dashboard_id])
    dashboard.metrics.order(:position).each_with_index { |metric, i| metric.update_attribute(:position, i + 1) }
    dashboard.metrics.find(params[:id]).move_to_bottom
    redirect_to dashboard_path(params[:dashboard_id])
  end

end

app/views/metrics/_form.html.erb
<%= form_for @metric, :html => { :class => 'form-horizontal' } do |f| %>
  <fieldset>
    <legend><%= controller.action_name.capitalize %> /Metric</legend>

    <div class="control-group">
      <%= f.label :name, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_field :name, :class => 'text_field' %>
      </div>
    </div>

    <div class="control-group">
      <%= f.label :value_type, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_field :value_type, :class => 'text_field' %>
      </div>
    </div>

    <div class="control-group">
      <%= f.label :string_value, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_field :string_value, :class => 'text_field' %>
      </div>
    </div>

    <div class="control-group">
      <%= f.label :integer_value, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_field :integer_value, :class => 'text_field' %>
      </div>
    </div>

    <div class="control-group">
      <%= f.label :color, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_field :color, :class => 'text_field' %>
      </div>
    </div>

    <div class="control-group">
      <%= f.label :width, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_field :width, :class => 'text_field' %>
      </div>
    </div>

    <div class="control-group">
      <%= f.label :font_size, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_field :font_size, :class => 'text_field' %>
      </div>
    </div>

    <div class="control-group">
      <%= f.label :refresh_every, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_field :refresh_every, :class => 'text_field' %>
      </div>
    </div>


    <div class="control-group">
      <%= f.label :description, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_area :description, :class => 'text_area' %>
      </div>
    </div>

    <div class="control-group">
      <%= hidden_field_tag "metric[dashboard_ids][]", nil %>
      <% Dashboard.all.each do |dashboard| %>
        <%= check_box_tag "metric[dashboard_ids][]", dashboard.id, @metric.dashboard_ids.include?(dashboard.id), id: dom_id(dashboard) %>
        <%= dashboard.name %><br/>
      <% end %>
    </div>

    <div class="form-actions">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to 'Cancel', metrics_path, :class => 'btn' %>
    </div>
  </fieldset>
<% end %>

app/views/metrics/_widget.html.erb
<% if metric.value_type == 'integer' %>
<div class="item" id="m<%= metric.id %>" data-refresh-every="<%= metric.refresh_every %>">
  <div class="inner">
    <div class="name"><%= metric.name %></div>
    <div class="number" style="font-size:<%= metric.font_size %>px;line-height:<%= metric.font_size %>px;color:<%= metric.color %>"><%= metric.integer_value %></div>
  </div>
</div>

<% elsif metric.value_type == 'line' %>

<div class="item" id="m<%= metric.id %>" data-refresh-every="<%= metric.refresh_every %>">
  <div class="inner">
    <div class="name"><%= metric.name %></div>
    <%= graph(metric, chart_width: 550, chart_height: 150, without_x: false, color: metric.color) %>
  </div>
</div>

<% elsif metric.value_type == 'knob' %>

<div class="item" id="m<%= metric.id %>" data-refresh-every="<%= metric.refresh_every %>">
  <div class="inner">
    <div class="name"><%= metric.name %></div>
    <div class="number">
      <input class="knob" data-bgColor="#555555" data-fgColor="<%= metric.color %>" data-thickness=".3" data-readOnly=true value="<%= metric.integer_value %>" data-width="110" style="height:30px;-webkit-box-shadow:none;box-shadow:none;">
    </div>
  </div>
</div>

<% elsif metric.value_type == 'percent' %>

<div class="item" id="m<%= metric.id %>" data-refresh-every="<%= metric.refresh_every %>">
  <div class="inner">
    <div class="title">123 PLATFORM</div>
    <div class="bar">
      <div class="bar-inner" style="width:60%;" data-item="iOS"></div>
      <div class="bar-inner" style="width:39%;" data-item="Android"></div>
    </div>
    <div class="number">iOS</div>
  </div>
</div>

<% else %>

<div class="item" id="m<%= metric.id %>" data-refresh-every="<%= metric.refresh_every %>">
  <div class="inner">
    <div class="name"><%= metric.name %></div>
    <div class="number" style="font-size:<%= metric.font_size %>px;line-height:<%= metric.font_size %>px;color:<%= metric.color %>"><%= metric.string_value %></div>
  </div>
</div>

<% end %>

app/views/metrics/edit.html.erb
<%= render :partial => 'form' %>

app/views/metrics/index.html.erb
<h1>Metrics</h1>
<table class="table table-striped">
  <thead>
    <tr>
      <th>ID</th>
      <th>Name</th>
      <th>Description</th>
      <th>Refresh every</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @metrics.each do |metric| %>
      <tr>
        <td><%= metric.id %></td>
        <td><%= metric.name %></td>
        <td><%= metric.description %></td>
        <td><%= metric.refresh_every %> seconds</td>
        <td>
          <%= link_to 'Edit', edit_metric_path(metric), :class => 'btn btn-mini' %>
          <%= link_to 'Destroy', metric_path(metric), :method => :delete, :confirm => 'Are you sure?', :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'New', new_metric_path, :class => 'btn btn-primary' %>

app/views/metrics/new.html.erb
<%= render :partial => 'form' %>

app/views/metrics/show.html.erb
<h1>Metric</h1>

<%= graph(@metric) %>

<div class="form-actions">
  <%= link_to 'Back', metrics_path, :class => 'btn'  %>
  <%= link_to 'Edit', edit_metric_path(@metric), :class => 'btn' %>
  <%= link_to 'Delete', metric_path(@metric), :method => 'delete', :confirm => 'Are you sure?', :class => 'btn btn-danger' %>
</div>