config/routes.rb
Board::Application.routes.draw do

  root to: 'dashboards#index'

  resources :metrics do
    collection { post :sort }
    member do
      get 'move_higher'
      get 'move_lower'
      get 'move_to_top'
      get 'move_to_bottom'
    end
  end

  resources :dashboards do
    member do
      get 'board'
    end
  end

  post 'api/stats', to: 'metrics#stats', as: :stats
  get 'help', to: 'welcome#help', as: :help

  get 'login', to: 'admin_sessions#new', as: 'login'
  get 'logout', to: 'admin_sessions#destroy', as: 'logout'
  resources :admin_sessions

end

app/models/dashboard.rb
class Dashboard < ActiveRecord::Base
  has_many :assignments
  has_many :metrics, :through => :assignments, :order => "position"
  attr_accessible :name, :description
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
  before_filter :authorize

  # GET /dashboards
  # GET /dashboards.json
  def index
    @dashboards = Dashboard.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @dashboards }
    end
  end

  # GET /dashboards/1
  # GET /dashboards/1.json
  def show
    @dashboard = Dashboard.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @dashboard }
    end
  end

  def board
    @dashboard = Dashboard.find(params[:id])
    render :layout => nil
  end

  # GET /dashboards/new
  # GET /dashboards/new.json
  def new
    @dashboard = Dashboard.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @dashboard }
    end
  end

  # GET /dashboards/1/edit
  def edit
    @dashboard = Dashboard.find(params[:id])
  end

  # POST /dashboards
  # POST /dashboards.json
  def create
    @dashboard = Dashboard.new(params[:dashboard])

    respond_to do |format|
      if @dashboard.save
        format.html { redirect_to @dashboard, notice: 'Dashboard was successfully created.' }
        format.json { render json: @dashboard, status: :created, location: @dashboard }
      else
        format.html { render action: "new" }
        format.json { render json: @dashboard.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /dashboards/1
  # PUT /dashboards/1.json
  def update
    @dashboard = Dashboard.find(params[:id])

    respond_to do |format|
      if @dashboard.update_attributes(params[:dashboard])
        format.html { redirect_to @dashboard, notice: 'Dashboard was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @dashboard.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /dashboards/1
  # DELETE /dashboards/1.json
  def destroy
    @dashboard = Dashboard.find(params[:id])
    @dashboard.destroy

    respond_to do |format|
      format.html { redirect_to dashboards_url }
      format.json { head :no_content }
    end
  end
end

app/views/dashboards/_form.html.erb
<%= form_for @dashboard, :html => { :class => 'form-horizontal' } do |f| %>
  <fieldset>
    <legend><%= controller.action_name.capitalize %> /Dashboard</legend>

    <div class="control-group">
      <%= f.label :name, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_field :name, :class => 'text_field' %>
      </div>
    </div>

    <div class="control-group">
      <%= f.label :description, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_area :description, :class => 'text_area' %>
      </div>
    </div>

    <div class="form-actions">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to 'Cancel', dashboards_path, :class => 'btn' %>
    </div>
  </fieldset>
<% end %>

app/views/dashboards/board.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>Board</title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
    <![endif]-->

    <!-- Le styles -->
    <%= stylesheet_link_tag "application", :media => "all" %>
    <link href="http://fonts.googleapis.com/css?family=Ubuntu:400,500" rel="stylesheet" type="text/css" />
    <link href="http://count.ly/stylesheets/webfonts.css" rel="stylesheet" type="text/css" />

    <style>
#board {
  padding-top: 0px;
  background-image: url(/assets/carbon_fibre.png); }

[class*="span"] {
  margin-left: 20px; }

.item {
  float: left;
  width: 100%;
  margin-top: 20px;
  font-family: 'AlternateGothicNo2BT-Regular';
  border-radius: 7px;
  border: 2px solid #333; }
 
.inner {
  height: 160px;
  padding: 10px;
  border-radius: 5px;
  background-image: -webkit-linear-gradient(top, #3C3C3C 10%, #2A2A2A 100%);
  margin-left: 5px; }
 
.item:first-child  .inner { margin-left: 0px; }
 
.item:first-child .inner { border-left: none; }
 
.item:last-child .inner { border-right: none; }
 
.item .name {
  font-size: 12px;
  text-align: center;
  color: #FFF;
  text-transform: uppercase;
  font-family: "Ubuntu"; }
 
.item .bar {
  width: 80%;
  height: 16px;
  padding-top: 2px;
  padding-bottom: 2px;
  overflow: auto;
  border-radius: 5px;
  background-color: transparent;
  margin: 0 auto;
  margin-top: 25px;
  margin-bottom: 5px; }
 
  .item .bar .bar-inner {
    background-color: #6BB96E;
    width: 40%;
    float: left;
    height: 16px;
    cursor: pointer;
    margin-left: 1%; }
 
    .item  .bar .bar-inner:hover {
      margin-bottom: -1px;
      margin-top: -1px;
      height: 18px; }
 
    .item  .bar .bar-inner:first-child {
      margin-left: 0px;
      border-top-left-radius: 5px;
      border-bottom-left-radius: 5px; }
 
    .item  .bar .bar-inner:last-child {
      border-top-right-radius: 5px;
      border-bottom-right-radius: 5px; }
 
    .item  .bar .bar-inner:nth-child(2) {
      background-color: #86CBDD;
      width: 42%; }
 
    .item .bar .bar-inner:nth-child(3) {
      background-color: #EC8C45;
      width: 16%; }
 
.item .number {
  font-size: 33px;
  text-align: center;
  color: #6BB96E;
  margin-top:20px; }

    </style>

    <!-- Le HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>
  </head>

  <body id="board">
    <div class="container">
      
      <div class="row">
      <% v = 0 %>
      <% @dashboard.metrics.each do |metric| %>
        <%
        if metric.value_type == 'string'
          v += 3
        elsif metric.value_type == 'line'
          v += 6
        end
        %>

        <% if v > 12 %>
          <% v = 0 %>
          </div>
          <div class="row">          
        <% end %>

        <div class="span<%= metric.width * 3 %>">
          <%= render partial: 'metrics/widget', locals: { metric: metric} %>
        </div>

      <% end %>
      </div>

    </div>

    <!-- Le javascript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <%= javascript_include_tag "application" %>
  </body>
</html>

app/views/dashboards/board_old.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>Board</title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
    <![endif]-->

    <!-- Le styles -->
    <%= stylesheet_link_tag "application", :media => "all" %>
    <link href="http://fonts.googleapis.com/css?family=Ubuntu:400,500" rel="stylesheet" type="text/css" />
    <link href="http://count.ly/stylesheets/webfonts.css" rel="stylesheet" type="text/css" />

    <style>
#board {
  padding-top: 0px;
  background-image: url(/assets/carbon_fibre.png); }

[class*="span"] {
  margin-left: 20px; }

.item {
  float: left;
  width: 100%;
  margin-top: 20px;
  font-family: 'AlternateGothicNo2BT-Regular';
  border-radius: 7px;
  border: 2px solid #333; }
 
.inner {
  height: 160px;
  padding: 10px;
  border-radius: 5px;
  background-image: -webkit-linear-gradient(top, #3C3C3C 10%, #2A2A2A 100%);
  margin-left: 5px; }
 
.item:first-child  .inner { margin-left: 0px; }
 
.item:first-child .inner { border-left: none; }
 
.item:last-child .inner { border-right: none; }
 
.item .name {
  font-size: 12px;
  text-align: center;
  color: #FFF;
  text-transform: uppercase;
  font-family: "Ubuntu"; }
 
.item .bar {
  width: 80%;
  height: 16px;
  padding-top: 2px;
  padding-bottom: 2px;
  overflow: auto;
  border-radius: 5px;
  background-color: transparent;
  margin: 0 auto;
  margin-top: 25px;
  margin-bottom: 5px; }
 
  .item .bar .bar-inner {
    background-color: #6BB96E;
    width: 40%;
    float: left;
    height: 16px;
    cursor: pointer;
    margin-left: 1%; }
 
    .item  .bar .bar-inner:hover {
      margin-bottom: -1px;
      margin-top: -1px;
      height: 18px; }
 
    .item  .bar .bar-inner:first-child {
      margin-left: 0px;
      border-top-left-radius: 5px;
      border-bottom-left-radius: 5px; }
 
    .item  .bar .bar-inner:last-child {
      border-top-right-radius: 5px;
      border-bottom-right-radius: 5px; }
 
    .item  .bar .bar-inner:nth-child(2) {
      background-color: #86CBDD;
      width: 42%; }
 
    .item .bar .bar-inner:nth-child(3) {
      background-color: #EC8C45;
      width: 16%; }
 
.item .number {
  font-size: 33px;
  text-align: center;
  color: #6BB96E;
  margin-top:20px; }

    </style>

    <!-- Le HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>
  </head>

  <body id="board">
    <div class="container">
      
      <div class="row">
      <% v = 0 %>
      <% @dashboard.metrics.each do |metric| %>
        <%
        if metric.value_type == 'string'
          v += 3
        elsif metric.value_type == 'line'
          v += 6
        end
        %>

        <% if v > 12 %>
          <% v = 0 %>
          </div>
          <div class="row">          
        <% end %>

        <div class="span<%= metric.width * 3 %>">
          <%= render partial: 'metrics/widget', locals: { metric: metric} %>
        </div>

      <% end %>
      </div>

    </div>

    <!-- Le javascript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <%= javascript_include_tag "application" %>
  </body>
</html>

app/views/dashboards/edit.html.erb
<%= render :partial => 'form' %>

app/views/dashboards/index.html.erb
<h1>Dashboards</h1>
<table class="table table-striped">
  <thead>
    <tr>
      <th>ID</th>
      <th>Name</th>
      <th>Created at</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @dashboards.each do |dashboard| %>
      <tr>
        <td><%= dashboard.id %></td>
        <td><%= link_to dashboard.name, dashboard_path(dashboard) %></td>
        <td><%= dashboard.created_at %></td>
        <td>
          <%= link_to 'Board', board_dashboard_path(dashboard), :class => 'btn btn-mini' %>
          <%= link_to 'Edit', edit_dashboard_path(dashboard), :class => 'btn btn-mini' %>
          <%= link_to 'Destroy', dashboard_path(dashboard), :method => :delete, :confirm => 'Are you sure?', :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'New', new_dashboard_path, :class => 'btn btn-primary' %>

app/views/dashboards/new.html.erb
<%= render :partial => 'form' %>

app/views/dashboards/show.html.erb
<h1>/Dashboard</h1>

<p>
  <b>Name</b><br>
  <%= @dashboard.name %>
</p>

<p>
  <b>Description</b><br>
  <%= @dashboard.description %>
</p>

<p>
  <b>Metrics</b><br>
</p>

<table class="table table-striped">
  <thead>
    <tr>
      <th style="width:20px">&nbsp;</th>
      <th>ID</th>
      <th>Position</th>
      <th>Name</th>
      <th>Description</th>
    </tr>
  </thead>
  <tbody id="metrics" data-update-url="<%= sort_metrics_url(dashboard_id: @dashboard.id) %>">
    <% @dashboard.metrics.each do |metric| %>
      <tr id="metric_<%= metric.id %>">
        <td>
          <div class="handle">
            <i class="icon-move" style="font-size:25px;"></i>
          </div>
        </td>
        <td><%= metric.id %></td>
        <td><%= metric.position %></td>
        <td><%= metric.name %></td>
        <td><%= metric.description %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<div class="form-actions">
  <%= link_to 'Back', dashboards_path, :class => 'btn'  %>
  <%= link_to 'Edit', edit_dashboard_path(@dashboard), :class => 'btn' %>
  <%= link_to 'Delete', dashboard_path(@dashboard), :method => 'delete', :confirm => 'Are you sure?', :class => 'btn btn-danger' %>
</div>