config/routes.rb
Board::Application.routes.draw do

  root to: 'dashboards#index'

  resources :metrics do
    collection { post :sort }
    member do
      get 'move_higher'
      get 'move_lower'
      get 'move_to_top'
      get 'move_to_bottom'
    end
  end

  resources :dashboards do
    member do
      get 'board'
    end
  end

  post 'api/stats', to: 'metrics#stats', as: :stats
  get 'help', to: 'welcome#help', as: :help

  get 'login', to: 'admin_sessions#new', as: 'login'
  get 'logout', to: 'admin_sessions#destroy', as: 'logout'
  resources :admin_sessions

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>123Board</title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
    <![endif]-->

    <!-- Le styles -->
    <%= stylesheet_link_tag "application", :media => "all" %>
  </head>
  <body data-spy="scroll" data-target=".subnav" data-offset="50">

    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
          <div class="container">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="#">123Board</a>
          <div class="container nav-collapse">
            <ul class="nav">
                <li><%= link_to "Dashboards", dashboards_path %></li>
                <li><%= link_to "Metrics", metrics_path %></li>
                <li><%= link_to "Help", help_path %></li>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container">

      <div class="content">
        <div class="row">
           <div class="span9">
             <% if notice %>
               <%= content_tag :div, notice, :class => "alert alert-success" %>
             <% end %>

             <% if alert %>
               <%= content_tag :div, alert, :class => "alert alert-error" %>
             <% end %>

             <%= yield %>
            </div>
        </div><!--/row-->
      </div><!--/content-->

      <footer>
        <p>&copy; Company 2012</p>
      </footer>

    </div> <!-- /container -->

    <!-- Le javascript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <%= javascript_include_tag "application" %>

  </body>
</html>
<%= ENV['HTTP_USER'] %>
<%= ENV['HTTP_PASS'] %>